config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    member do
      get :reviewing, :reviewers
    end
  end
  resources :dealings, only: [:create, :new, :show] do
    member do
      patch :update_to_delivering
      patch :update_to_completed
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :items,               only: [:new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments,            only: [:create]
  resources :likes,               only: [:create, :destroy]
  resources :reviews,             only: :create
end

app/models/dealing.rb
class Dealing < ApplicationRecord
  include DealingsHelper

  ### ASSOCIATION
  belongs_to :seller, class_name: "User"
  belongs_to :buyer,  class_name: "User"
  belongs_to :item
  has_many :reviews, dependent: :destroy

  ### VALIDATION
  validates :item_id, presence: true
  validates :buyer_id, presence: true
  validates :seller_id, presence: true
  validates :status, presence: true

  enum status: {
      payed: 1,
      delivering: 2,
      completed: 3
  }

  ### FUNCTION
  def seller?(user)
    self.seller == user
  end

  def buyer?(user)
    self.buyer == user
  end

  def accessible_user?(user)
    self.seller?(user) || self.buyer?(user)
  end

  def already_reviewed?(user)
    review = Review.find_by(dealing_id: self.id, reviewer_id: user.id)
    review.blank?
  end

end

app/controllers/dealings_controller.rb
class DealingsController < ApplicationController
  include DealingsHelper

  before_action :logged_in_user
  before_action :correct_seller_or_buyer, only: [:show]

  def show
    @dealing = Dealing.find(params[:id])
    @item = @dealing.item
  end

  def create
    @item = Item.find(params[:item_id])
    redirect_to root_path if current_user == @item.user

    @dealing = @item.build_dealing(
        buyer: current_user,
        seller: @item.user
    )

    if @dealing.save
        flash[:success] = "商品を購入しました"
        redirect_to dealing_path(@dealing)
    else
        flash[:danger] = "商品を購入できませんでした"
        render 'new'
    end
  end

  def new
    @item = Item.find(params[:item_id])
    @dealing = @item.build_dealing
  end

  def update_to_delivering
    @dealing = Dealing.find(params[:id])
    @dealing.delivering!
    redirect_to dealing_path
  end

  def update_to_completed
    @dealing = Dealing.find(params[:id])
    @dealing.completed!
    redirect_to dealing_path
  end

  private

    def correct_seller_or_buyer
      dealing = Dealing.find(params[:id])
      redirect_to root_url unless dealing.accessible_user?(current_user)
    end


end

app/helpers/dealings_helper.rb
module DealingsHelper
end

app/views/dealings/_review.html.erb
<% if @dealing.already_reviewed?(current_user) %>
<div class="review">
    <h2>この取引を評価しましょう</h2>
   <div class="review-form">
      <%= form_for(@dealing.reviews.build) do |f| %>
        <div><%= hidden_field_tag :dealing_id, @dealing.id %></div>
        <div><%= hidden_field_tag :evaluation, 1 %></div>
        <%= button_tag(class: "review-btn") do %>
          <i class="far fa-smile-wink"></i>
        <% end %>
      <% end %>

    <%= form_for(@dealing.reviews.build) do |f| %>
      <div><%= hidden_field_tag :dealing_id, @dealing.id %></div>
      <div><%= hidden_field_tag :evaluation, 2 %></div>
      <%= button_tag(class: "review-btn") do %>
        <i class="far fa-meh"></i>
      <% end %>
    <% end %>

    <%= form_for(@dealing.reviews.build) do |f| %>
      <div><%= hidden_field_tag :dealing_id, @dealing.id %></div>
      <div><%= hidden_field_tag :evaluation, 3 %></div>
      <%= button_tag(class: "review-btn") do %>
        <i class="far fa-frown"></i>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

app/views/dealings/confirm.html.erb
<h2>購入内容の確認</h2>


<div class="item">
  <%= image_tag @item.picture.url, {class: "picture"} %>
  <%= @item.name %><br>
  価格:<%= @item.price.to_s(:delimited) %>円<br>
</div>

<%= render "items/buy", item: @item %>
<%= link_to "戻る", (item_path(@item)), class: "btn btn-primary" %>

app/views/dealings/new.html.erb
<div class="item-box">
  <h2>購入内容の確認</h2>
  <h4>出品者:<%= @item.user.name %></h4>
  <%= image_tag @item.image, {class: "picture"} if @item.image.attached? %>
  <%= @item.name %><br>
  価格:<%= @item.price.to_s(:delimited) %>円<br>

  <%= form_for(@dealing) do |f| %>
    <%= hidden_field_tag :item_id, @item.id %>
    <%= f.submit "購入する", class: "red-button" %>
  <% end %>
</div>

app/views/dealings/show.html.erb
<div class="item">
  <h2>取引詳細</h2>
  <h3>現在の取引状況：<%= @dealing.status_i18n %></h3>

  <%= @item.name %><br>
  <h3>出品者:<%= @dealing.seller.name %></h3>
  <h3>購入者:<%= @dealing.buyer.name %></h3>
  <%= image_tag @item.image, {class: "picture"} if @item.image.attached? %><br>
  価格:<%= @item.price.to_s(:delimited) %>円<br>
<!--  出品者ページ-->
  <% if @dealing.seller?(current_user) %>
    <% if @dealing.payed? %>
      <h3>購入者住所：dealing.user.address</h3>
      <h3><%= @item.days_to_ship %>してください</h3>
      <%= link_to "発送完了", update_to_delivering_dealing_path, method: :patch %>
    <% end %>
<!--    購入者ページ-->
  <% elsif @dealing.buyer?(current_user) %>
    <% if  @dealing.delivering? %>
      <%= link_to "商品が到着", update_to_completed_dealing_path, method: :patch %>
    <% end %>
  <% end %>
  <% if @dealing.completed? %>
    <%= render "dealings/review", dealing: @dealing %>
  <% end %>
</div>