config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    member do
      get :reviewing, :reviewers
    end
  end
  resources :dealings, only: [:create, :new, :show] do
    member do
      patch :update_to_delivering
      patch :update_to_completed
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :items,               only: [:new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments,            only: [:create]
  resources :likes,               only: [:create, :destroy]
  resources :reviews,             only: :create
end

app/models/item.rb
class Item < ActiveRecord::Base

  ### ASSOCIATION

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :dealing, dependent: :destroy
  has_one_attached :image

  ###  VALIDATIONS

  default_scope -> { order(created_at: :desc) }
  # mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  # validate  :picture_size
  # validates :picture, presence: true
  validates :seller_area, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :price, presence: true, :numericality => { :greater_than => 0 }
  validates :category, presence: true
  validates :days_to_ship, presence: true
  validates :condition, presence: true
  validates :shipping_fee, presence: true


  enum category: {
      レディース:1, メンズ:2, ベビー・キッズ:3, インテリア・住まい・小物:4,
      本・音楽・ゲーム:5, おもちゃ・ホビー・グッズ:6, コスメ・香水・美容:7, 家電・スマホ・カメラ:8,
      スポーツ・レジャー:9, ハンドメイド:10, チケット:11, 自動車・オートバイ:12, その他:13
  }

  enum seller_area: {
      北海道:1, 青森県:2, 岩手県:3, 宮城県:4, 秋田県:5, 山形県:6, 福島県:7,
      茨城県:8, 栃木県:9, 群馬県:10, 埼玉県:11, 千葉県:12, 東京都:13, 神奈川県:14,
      新潟県:15, 富山県:16, 石川県:17, 福井県:18, 山梨県:19, 長野県:20,
      岐阜県:21, 静岡県:22, 愛知県:23, 三重県:24,
      滋賀県:25, 京都府:26, 大阪府:27, 兵庫県:28, 奈良県:29, 和歌山県:30,
      鳥取県:31, 島根県:32, 岡山県:33, 広島県:34, 山口県:35,
      徳島県:36, 香川県:37, 愛媛県:38, 高知県:39,
      福岡県:40, 佐賀県:41, 長崎県:42, 熊本県:43, 大分県:44, 宮崎県:45, 鹿児島県:46,
      沖縄県:47
  }

  enum condition: {
      新品、未使用:1, 未使用に近い:2, 目立った傷や汚れなし:3,　やや傷や汚れあり:4, 傷や汚れあり:5
  }

  enum days_to_ship: {
      "1~2日で発送":1, "2~3日で発送":2, "4~7日で発送":3
  }

  enum shipping_fee: {
      出品者負担:1, 購入者負担:2
  }

  def sold?
    dealing.present?
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def show
    @item = Item.find(params[:id])
    @dealing = @item.dealing
    @comment = @item.comments.build
    @review = Review.where(reviewed_id: @item.user_id)
  end

  def new
    @item  = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "Item created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @item.destroy
    flash[:success] = "Item deleted"
    redirect_to root_url
  end



  private

  def item_params
    params.require(:item).permit(
        :content, :picture, :seller_area, :name, :price,
        :category, :days_to_ship, :condition, :shipping_fee, :image
    )
  end

  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    redirect_to root_url if @item.nil?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_delete.html.erb
<span class="timestamp">
    Posted <%= time_ago_in_words(item.created_at) %> ago.
  <% if current_user?(item.user) %>
      <%= link_to "delete", item, method: :delete,
                      data: { confirm: "You sure?" } %>
  <% end %>
</span>

app/views/items/_item.html.erb
  <section class="card" id="item-<%= item.id %>">
    <%= link_to(item_path(item)) do %>
    <div class="card-picture">
        <%= image_tag item.image, {class: "picture"} if item.image.attached? %>
      <%= render "items/like", item: item %>
      <p>¥<%= item.price.to_s(:delimited) %></p>
      <% if item.sold? %>
        <div class="sold-mark">SOLD</div>
      <% end %>
    </div>
    <div class="card-content">
      <%= item.name %>
    </div>
<% end %>
  </section>

app/views/items/_item_table.html.erb
<table class="item-detail-table" >
  <tbody>
  <tr>
    <td>出品者</td>
    <td><%= link_to @item.user.name, @item.user %> <br>
      <i class="far fa-smile-wink"> <%= @review.where(evaluation: 1).count %>  </i>
      <i class="far fa-meh"> <%= @review.where(evaluation: 2).count %>  </i>
      <i class="far fa-frown"> <%= @review.where(evaluation: 3).count %>  </i>
    </td>
  </tr>
  <tr>
    <td>カテゴリー</td>
    <td><%= @item.category %></td>
  </tr>
  <tr>
    <td>商品の状態</td>
    <td><%= @item.condition %></td>
  </tr>
  <tr>
    <td>配送料の負担</td>
    <td><%= @item.shipping_fee %></td>
  </tr>
  <tr>
    <td>配送元地域</td>
    <td><%= @item.seller_area %></td>
  </tr>
  <tr>
    <td>発送日の目安</td>
    <td><%= @item.days_to_ship %></td>
  </tr>
  </tbody>
</table>

app/views/items/_like.html.erb
<div class="like">
  <% if current_user.already_liked?(item) %>
   <%= form_for(item.likes.find_by(item_id: item.id),method: :delete, remote: true ) do |f| %>
      <div><%= hidden_field_tag :item_id, item.id %></div>
      <%= button_tag(class: "like-btn") do %>
        <span class="glyphicon glyphicon-heart"></span>
     <% end %>
   <% end %>
  <% else %>
   <%= form_for(item.likes.build) do %>
     <div><%= hidden_field_tag :item_id, item.id %></div>
     <%= button_tag(class: "unlike-btn") do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
     <% end %>
   <% end %>
  <% end %>
</div>

app/views/items/new.html.erb
<section class="item_form">
  <%= render 'shared/item_form', item: @item %>
</section>

app/views/items/show.html.erb
<div class="item-box">
  <h2><%= @item.name %></h2>
  <div class="main-content">
      <%= image_tag @item.image , {class: "picture"} if @item.image.attached? %>
      <%= render "items/item_table", item: @item %>
  </div>
  <br>
  <div class="price-box">
    <span class="item-price">¥<%= @item.price.to_s(:delimited) %></span>
    <% if @item.shipping_fee == '出品者負担' %>
      <span class="shipping-fee">送料込み</span>
    <% else %>
      <span class="shipping-fee">着払い</span>
    <% end %>
  </div>
  <div>
    <% if @item.sold? %>
      <% if @dealing.seller == current_user || @dealing.buyer == current_user %>
        <%= link_to "取引ページ", dealing_path(@item.dealing), class: "gray-button" %>
      <% else %>
        <div class="gray-button">売り切れました</div>
      <% end %>
    <% else %>
      <% if @item.user != current_user %>
        <%= link_to "購入画面に進む", new_dealing_path(:item_id => @item.id), class: "red-button" %>
      <% end %>
    <% end %>
  </div>
  <h3><%= @item.content %></h3>
  <p><%= render "items/like", item: @item %></p>
</div>

<div class="comment-box">
  <div class="comment-feed">
    <h4>Comments</h4>
    <% @item.comments.each do |comment| %>
      <h4>
        <%= comment.content %>
      </h4>
    <% end %>
  </div>

  <div class="comment-form">
    <%= form_for(@comment) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, placeholder: "相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。" %>
      </div>
      <div class="field-hide">
        <%= f.hidden_field :item_id, value: @item.id %>
      </div>
      <%= f.submit "コメントする", class: "gray-button" %>
    <% end %>
  </div>
</div>

<span class="timestamp">
    <%= render "items/delete", item: @item %>
</span>